imi-app/main/default/src/objects/Integration_Message_Incoming__c/Integration_Message_Incoming__c.object-meta.xml
<CustomObject>
    <label>Integration Message - Incoming</label>
    <nameField>
        <displayFormat>IMI-{0000}</displayFormat>
        <label>Integration Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Messages - Incoming</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Integration_Message_Incoming__c/fields/Command__c.field-meta.xml
<CustomField>
    <fullName>Command__c</fullName>
    <label>Command</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create_Opportunity</fullName>
            </value>
            <value>
                <fullName>Create_Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Integration_Message_Incoming__c/fields/Command_Argument__c.field-meta.xml
<CustomField>
    <fullName>Command_Argument__c</fullName>
    <inlineHelpText>The data schema for a command&#39;s argument is defined elsewhere.</inlineHelpText>
    <label>Command_Argument</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/classes/Integration_Message_HandlersTest.cls
@IsTest
private class Integration_Message_HandlersTest {
    @IsTest
    static void testIMI() {

        String createComments = 'Test Create Opp';
        
        Test.startTest();
        String oppExternalId = '123abc';
        Opportunity oppBefore = new Opportunity(
                Name = 'TestOpp',
                External_ID__c = oppExternalId,
                StageName = 'Draft',
                CloseDate = System.today().addMonths(1)
        );
        insert new Integration_Message_Incoming__c(
                Command__c = 'Create_Opportunity',
                Command_Argument__c = JSON.serialize(new IMI_Create_Opportunity_Arg(oppExternalId, oppBefore))
        );
        Test.stopTest();

        Opportunity oppAfter = [SELECT Id, Name FROM Opportunity WHERE External_ID__c = :oppExternalId];
        System.assertEquals(1, oppAfter.size());
    }

}